### ISSUE TITLE
didn't work

### ISSUE THREAD

**Issue by casoetan** [kbsali/sf2-icu#1]
I've been trying and still this hack didn't work, maybe you could help

**Comment by kbsali** [comment]
What is the value of ICU_DATA_VERSION in vendor/symfony/symfony/src/Symfony/Component/Locale/Locale.php?

**Comment by casoetan** [comment]
Hello
It is ICU_DATA_VERSION = '49' but I've sort of fixed it by adding it to the .htaccess file, but any other solutions will be good to know.

**Comment by kbsali** [comment]
What i've done was to implement a composer post install/update scripthandler to update ICU_DATA_VERSION's value : https://gist.github.com/kbsali/5442372

**Comment by casoetan** [comment]
That will great and easier thanks

Sent from my iPhone

On 23 Apr 2013, at 11:08, Kevin Saliou notifications@github.com wrote:

What i've done was to implement a composer post install/update
scripthandler to update ICU_DATA_VERSION's value, i'll create a gist

—
Reply to this email directly or view it on
GitHubhttps://github.com/kbsali/sf2-icu/issues/1#issuecomment-16849647
.

**Comment by vitts** [comment]
Can you please give me icu files version 46 for sf2.2.2.

**Comment by kbsali** [comment]
closing, all this issue has been fixed in sf 2.3..4.*
